# Generated by Django 5.2.11 on 2026-02-22 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='customer name')),
                ('amount', models.DecimalField(decimal_places=2, help_text="Amount in the currency's major unit (e.g., KES, USD).", max_digits=12, verbose_name='amount')),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('NGN', 'Nigerian Naira')], default='KES', max_length=3, verbose_name='currency')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='payment reference')),
                ('paystack_id', models.CharField(blank=True, max_length=100, verbose_name='Paystack transaction ID')),
                ('authorization_url', models.URLField(blank=True, verbose_name='Paystack authorization URL')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20, verbose_name='status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
