# Generated by Django 5.2.11 on 2026-02-22 19:13

import apps.payments.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='service name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('api_key', models.CharField(db_index=True, default=apps.payments.models.generate_api_key, max_length=64, unique=True, verbose_name='API key')),
                ('api_secret', models.CharField(default=apps.payments.models.generate_api_secret, max_length=80, verbose_name='API secret')),
                ('webhook_url', models.URLField(blank=True, help_text='URL to receive payment event notifications.', verbose_name='webhook callback URL')),
                ('default_callback_url', models.URLField(blank=True, help_text='Default URL to redirect users after payment.', verbose_name='default redirect URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('allowed_currencies', models.JSONField(blank=True, default=list, help_text='List of currency codes, e.g. ["KES","USD"]. Empty = all.', verbose_name='allowed currencies')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('logo_url', models.URLField(blank=True, verbose_name='logo URL')),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='List of IPs allowed to call the API. Empty = all.', verbose_name='allowed IP addresses')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
            ],
            options={
                'verbose_name': 'service product',
                'verbose_name_plural': 'service products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='callback_url',
            field=models.URLField(blank=True, help_text='URL to redirect user after payment.', verbose_name='payment callback URL'),
        ),
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(blank=True, help_text='Payment channel (card, bank, ussd, etc.)', max_length=50, verbose_name='payment channel'),
        ),
        migrations.AddField(
            model_name='payment',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fees charged by Paystack.', max_digits=12, verbose_name='Paystack fees'),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='idempotency key'),
        ),
        migrations.AddField(
            model_name='payment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='client IP'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_refund_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Paystack refund ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(choices=[('none', 'No Refund'), ('pending', 'Refund Pending'), ('partial', 'Partially Refunded'), ('full', 'Fully Refunded'), ('failed', 'Refund Failed')], default='none', max_length=20, verbose_name='refund status'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='refunded amount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_reference',
            field=models.CharField(blank=True, help_text="External service's order/transaction ID.", max_length=255, verbose_name='service reference'),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_delivered',
            field=models.BooleanField(default=False, verbose_name='webhook delivered'),
        ),
        migrations.AddField(
            model_name='payment',
            name='webhook_delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='webhook delivered at'),
        ),
        migrations.AddField(
            model_name='payment',
            name='service',
            field=models.ForeignKey(blank=True, help_text='The service/product that initiated this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.serviceproduct'),
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='webhook URL')),
                ('event', models.CharField(max_length=50, verbose_name='event type')),
                ('request_headers', models.JSONField(default=dict, verbose_name='request headers')),
                ('request_body', models.JSONField(default=dict, verbose_name='request body')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='response status code')),
                ('response_body', models.TextField(blank=True, verbose_name='response body')),
                ('attempt', models.IntegerField(default=1, verbose_name='attempt number')),
                ('success', models.BooleanField(default=False, verbose_name='successful')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='duration (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='payments.payment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='payments.serviceproduct')),
            ],
            options={
                'verbose_name': 'webhook delivery log',
                'verbose_name_plural': 'webhook delivery logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
