# Generated by Django 5.2.11 on 2026-02-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_serviceproduct_payment_callback_url_payment_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Exchange rate used: 1 <original currency> = X KES.', max_digits=18, null=True, verbose_name='exchange rate'),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in KES sent to Paystack after conversion.', max_digits=12, null=True, verbose_name='settlement amount (KES)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="Original amount in the client's currency.", max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('NGN', 'Nigerian Naira'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('GHS', 'Ghanaian Cedi'), ('ZAR', 'South African Rand'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('RWF', 'Rwandan Franc'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('AED', 'UAE Dirham'), ('CHF', 'Swiss Franc'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('MXN', 'Mexican Peso'), ('BRL', 'Brazilian Real'), ('ETB', 'Ethiopian Birr'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('XOF', 'West African CFA Franc'), ('XAF', 'Central African CFA Franc'), ('BWP', 'Botswana Pula'), ('MUR', 'Mauritian Rupee'), ('SCR', 'Seychellois Rupee'), ('ZMW', 'Zambian Kwacha'), ('MWK', 'Malawian Kwacha')], default='KES', help_text='Original currency submitted by the client.', max_length=3, verbose_name='currency'),
        ),
    ]
