# Generated by Django 5.2.14 on 2026-05-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_exchange_rate_payment_settlement_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproduct',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Mark as test product to use Paystack test credentials.', verbose_name='test product'),
        ),
    ]
