# Generated by Django 5.2.14 on 2026-05-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_serviceproduct_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproduct',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='bank account number'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='charge_bearer',
            field=models.CharField(choices=[('account', 'Main account'), ('subaccount', 'Subaccount')], default='account', help_text='Who bears Paystack processing fees.', max_length=20, verbose_name='Paystack fee bearer'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='percentage_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage Acoruss (main account) keeps from each payment.', max_digits=5, null=True, verbose_name='platform percentage'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='settlement_bank',
            field=models.CharField(blank=True, help_text='Paystack bank code for settlement.', max_length=20, verbose_name='settlement bank code'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='settlement_bank_name',
            field=models.CharField(blank=True, help_text='Human-readable bank name.', max_length=255, verbose_name='settlement bank name'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='subaccount_business_name',
            field=models.CharField(blank=True, help_text='Partner business name for the subaccount.', max_length=255, verbose_name='subaccount business name'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='subaccount_code',
            field=models.CharField(blank=True, help_text='Paystack subaccount code (e.g. ACCT_xxx). Auto-generated.', max_length=100, verbose_name='Paystack subaccount code'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='subaccount_paystack_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Paystack subaccount ID'),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='transaction_charge',
            field=models.IntegerField(blank=True, help_text='Flat fee Acoruss keeps per transaction (in smallest currency unit).', null=True, verbose_name='flat transaction charge (kobo)'),
        ),
    ]
