# Generated by Django 5.2.11 on 2026-02-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactsubmission_company_contactsubmission_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='project_type',
            field=models.CharField(blank=True, choices=[('website', 'Website Development'), ('custom_software', 'Custom Software'), ('ai_automation', 'AI & Automation'), ('consulting', 'Strategy & Consulting'), ('security', 'Security & Trust'), ('other', 'Other')], default='', max_length=100),
        ),
    ]
